version: "3"

services:
  db:
    image: "mongo:bionic"
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  api:
    build: ./api/
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
  frontend:
    build: ./frontend/
    ports:
      - 80:4200
    restart: always
    depends_on:
      - api
